apiVersion: "app.phil.com/v1alpha1"
kind: "PhilsThing"
metadata:
  name: "example"
spec:
  service_class_name: "dh-android-app-apb"
  params:
    appIdentifier: "org.pbrookes.android"
    appName: "phils-app"