apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: philsthings.app.phil.com
spec:
  group: app.phil.com
  names:
    kind: philsThing
    listKind: philsThingList
    plural: philsthings
    singular: philsthing
  scope: Namespaced
  version: v1alpha1
