apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: philsthings.app.phil.com
spec:
  group: app.phil.com
  names:
    kind: PhilsThing
    listKind: PhilsThingList
    plural: philsthings
    singular: philsthing
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            service_class_name:
              type: string
            params:
              description: parameters for creating the services
              type: object